# Generated by Django 3.2.8 on 2021-10-20 22:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymus', max_length=14, verbose_name='Name')),
                ('body', models.CharField(db_index=True, max_length=140, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created_ DateTime')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
