# Generated by Django 3.2.8 on 2021-10-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTwitterApp', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
